name: Ubuntu 20.04 Swift CI

on:
  push:
    branches: [development, main]

jobs:

  exec-ci:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Configure
        run: cmake -G "Unix Makefiles" -B .build

      - name: Build
        run: cd .build && make
